---
abstract: 'terminal key input using C<libtermkey> with C<POE>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires: {}
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Wheel-TermKey
provides:
  POE::Wheel::TermKey:
    file: lib/POE/Wheel/TermKey.pm
    version: 0.02
requires:
  POE: 0
  Term::TermKey: 0.08
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
